GaiaNet-AI/gaianet-node

- README.md
- install-gaia.sh
In this PR, add the installer script `install-gaia.sh`.
> feat: add `install-gaia.sh`

- README.md
Update `README` with an example
> doc: update `README`

- README.md
> fix: update `README`

- dashboard/index.html
- dashboard/js/abi.json
- dashboard/js/config.js
- dashboard/js/connect.js
- dashboard/js/interact.js
Implemented features:
- Create a static web
- Deployed a test contract on cybermiles which address is 0x2d096dF13dEE503b0E0A8383fDb56b149F631A73.
The contract address and ABI can be setted in `dashboard/js/config.js`.
> Create a static web page to register / update a LlamaEdge server

- demo/README.md
- demo/config.json
- demo/config.sh
- demo/init.sh
- demo/start.sh
Add shell script for the coming demonstration.
> feat: add scripts for demo

- demo/README.md
- demo/config.json
- demo/init.sh
- demo/start.sh
Major changes:
- New `--reinstall` CLI argument in `init.sh`
- Update Qdrant collection recovery priority to `snapshot`
> feat: add `--reinstall` CLI argument for `init.sh`

- demo/RAG.md
- demo/init.sh
- demo/install.txt
- demo/stop.sh
Major changes:
- Update `init.sh` to provide support for creating Qdrant collection from files with `txt` and `md` extensions.
> feat: support for creating Qdrant collection from text and markdown files

- demo/config.json
- demo/init.sh
- demo/start.sh
Major changes:
- Add the metadata of chat and embedding models to `config.json`
- Update `init.sh` and `start.sh` for the updated `config.json`
> feat: add model metadata to `config.json`

- demo/init.sh
- demo/start.sh
1. Update frpc subdomain to use HTTPS
2. Use port 443 instead of 8080
> Update frpc subdomain URL to use HTTPS

- demo/start.sh
Limit the server access to the `./dashboard` directory
> Make the server safer

- demo/init.sh
We use the registry.wasm to generate a pair of address and private key for the node, and write the information into config.json
> Add node ID

- utils/registry/Cargo.toml
- utils/registry/src/main.rs
- Generate a random password when the password field is empty. #13
> Generate random password

- .github/workflows/runNode.yml
- Use TinyLlama instead of Llama-2-7B on CI
> ci: add workflow to run and test node 

- v2/README.md
- v2/gaianet
- v2/install.sh
Major changes:
- New installation directory of CLI tool: `$HOME/bin`
- New command-line usage of CLI tool: `gaianet --help`, for example
> chore: update installation dir of cli tool

- .github/workflows/runNode_v2.yml
- v2/README.md
- v2/gaianet
- v2/install.sh
Major changes:
- Support `--base` arg in each subcommand of CLI tool
- Update `README`
> refactor: support `--base` arg in each subcommand

- .github/workflows/runNode_v2.yml
- v2/gaianet
- v2/install.sh
Major changes:
- Install `gaianet` CLI tool as root
> Refactor cli tool installation

- v2/gaianet
- v2/install.sh
Major changes:
- Improve v2 installer
- Improve CLI tool
> Improve installer

- gaianet
In `gaianet init`, we need to update the domain settings based on the current `config.json`
> Setup domain in init

- gaianet
- install.sh
Major changes:
- Introduce `llama-api-server.wasm` into installer and CLI tool
- Improve CLI tool
> feat: support empty snapshot

- README-cn.md
> doc: Add Chinese README

- frpc.toml
- gaianet
- install.sh
This pull request includes the following changes:
- Update frpc.toml Configuration: Modified the serverAddr to use a domain name instead of an IP address.
- Upgraded the gaianet-domain dependency to version 0.1.1.
> chore: Update frpc.toml with new server address and subdomain

- README.tr.md
This pull request adds a Turkish translation of the README.md file. The following changes have been made:
Created a new file README.tr.md with the Turkish translation of the content in README.md.
Updated README.md to include a link to the Turkish version at the top of the file.
Providing documentation in multiple languages can help non-English speaking contributors and users better understand and engage with the project. Adding a Turkish translation helps to make the project more accessible to Turkish speakers.
How Has This Been Tested?
• Proofread the Turkish translation for accuracy and completeness.
• Verified that the link to README.tr.md in README.md works correctly.
> Add Turkish translation of README.md

- uninstall.sh
Major change:
- Introduce `uninstall.sh` for uninstalling `gaianet-node`.
> feat: add uninstaller script

- .github/workflows/release.yml
- .github/workflows/runNode.yml
- gaianet
- install.sh
- vector.toml
Major changes:
- Installer
- Add `--enable-vector` CLI option for the installation of `Vector` log aggregator
- Install `Vector` log aggregator and download the configuration file `vector.toml`
- CLI tool
- Refactor `gaianet start` to support both local logging and using `Vector` log aggregator
- Add `vector.toml` as the default vector configuration
> feat: support for logging feature

- gaianet
- install.sh
Major change:
- Add `--upgrade` CLI option in `install.sh`
> feat: add `--upgrade` CLI option in installer

- gaianet
Fix Invalid `frpc.toml''` File Creation During `gaianet init`
> feat: Remove unnecessary files in gaianet-domain directory

- docker/README.md
> docs: update docker/README.md

- README-ar.md
- README.md
**Description**
This pull request adds Arabic Translation for `README.md`, and updates `README.md` accordingly. furthermore, it has 2 commits that do the following:
- create README-ar.md
- Update README.md
**Checklist**
---
If there are any issues, I'll be happy to fix them.
> Add Arabic Translation of `README.md`

- docker/README.md
Add content about regenerate node Id.
Change a typo "THen" by the way.
> Update README.md for regenerate node Id

- README-id.md
Hellow, im adding indonesian translation on README.md file. im translate this based on KBBI (Kamus Besar Bahasa Indonesia) so it must to be readable by everyone that know indonesian language
> mod (README.md) adding Indonesia translation

- .github/workflows/runNode.yml
- config.json
- gaianet
- install.sh
Major changes:
- Introduce `server-assistant` app
- `PUSH` server info to the target URL specified by `server_info_url` field in `config.json`
- `PUSH` server health periodically to the target URL specified by `server_health_url` field in `config.json`
> feat: introduce server-assistant

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This pull request adds in updates for the contribution guideline and code of conduct. It also makes changes to the Readme for contributors that come to the repository. 
The next steps for this will be to translate the remaining section of the Readme that I just added and the contributing guidelines to the other languages as well as other improvements to the Readme such as in-linking and the rest.
To put together the contribution guideline, I had to go through several files within the repository and set things up locally to put this all together. Thank you.
> feat: add contribution guideline and code of conduct

- README-ru.md
> translate README.md to Russia

- README-kr.md
- README.md
##Summary
This Update contains the README translation in Korean according to issue #177 
Kindly review.
@tobySolutions
> Translated README to korean

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
@tobySolutions I have added bug report, feature request and PR template addressed in issue #191
> Added bug report, feature request and pull request template

- docker/README.md
File have typo that need fix:
"initailize" ----> "initialize"
> fix typo in Update README.md
